{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.rock.spi",
    "module": "serviceloader",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "serviceloader-0.0.2.jar",
          "url": "serviceloader-0.0.2.jar",
          "size": 2686,
          "sha512": "7c2ab69444f4f312d488cddb213d3fecd1846fe6edea67295a4c8329de2754174ad2e0ad4a612e2f11c69fc866c8928b8dafe3db8bd8908a9c04e48f7a291471",
          "sha256": "b1be03be4161fe56326a20328fdc6f6a6966e9bfeb61e065977aac08fa372804",
          "sha1": "e87b64087b5d4622d59f02789bebcbdf4e53d4d4",
          "md5": "63bb2d8d5b2bb5a9f64f838dba8c5590"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "serviceloader-0.0.2.jar",
          "url": "serviceloader-0.0.2.jar",
          "size": 2686,
          "sha512": "7c2ab69444f4f312d488cddb213d3fecd1846fe6edea67295a4c8329de2754174ad2e0ad4a612e2f11c69fc866c8928b8dafe3db8bd8908a9c04e48f7a291471",
          "sha256": "b1be03be4161fe56326a20328fdc6f6a6966e9bfeb61e065977aac08fa372804",
          "sha1": "e87b64087b5d4622d59f02789bebcbdf4e53d4d4",
          "md5": "63bb2d8d5b2bb5a9f64f838dba8c5590"
        }
      ]
    }
  ]
}
